services:
  app:
    volumes:
      - '/home/laravel/storage/warehouse-manager:/var/www/${CONTAINER_NAME}/storage'
  mariadb:
    volumes:
      - '/home/laravel/database/warehouse-manager:/var/lib/mysql'
